### ISSUE TITLE
What's the dataset format for this project?

### ISSUE THREAD

**Issue by iVanlIsh** [xhzdeng/crpn#14]
I've tried scripts in data folder but seems the links are expired.
Then I tried to download dataset from http://host.robots.ox.ac.uk/pascal/VOC/voc2007/, and could not successfully run the code, too.
Please help me.
（也尝试魔改输入数据处理的代码，还是失败了，萌新求助QAQQQ）

**Comment by xhzdeng** [comment]
Unlike PascalVOC use [xmin, ymin, xmax, ymax] to make annotations, we utilize [x1, y1, x2, y2, x3, y3, x4, y4] to represent a object instance. So the [bndbox] field needs to have the following content:

```
<bndbox>
		<x1>158</x1>
		<y1>128</y1>
		<x2>158</x2>
		<y2>181</y2>
		<x3>411</x3>
		<y3>181</y3>
		<x4>411</x4>
		<y4>128</y4>
</bndbox>
```

The others are the same with PascalVOC. ^_^

**Comment by iVanlIsh** [comment]
I've changed that, but when I ran the project, it told me:
~~~
Loading pretrained model weights from models/pretrain.caffemodel
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "../lib/fast_rcnn/train.py", line 53, in __init__
    self.solver.net.layers[0].set_roidb(roidb)
  File "../lib/roi_data_layer/layer.py", line 69, in set_roidb
    self._shuffle_roidb_inds()
  File "../lib/roi_data_layer/layer.py", line 36, in _shuffle_roidb_inds
    inds = np.reshape(inds, (-1, 2))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 5011 into shape (2)
~~~
Is it because I cannot just run it with original training/validation data of VOC 2007?

**Comment by PeiChenPing** [comment]
I  met the same problem ,have you solved this? @iVanlIsh

**Comment by iVanlIsh** [comment]
@PeiChenPing not yet

**Comment by xhzdeng** [comment]
@iVanlIsh @PeiChenPing The number of images must be even.

**Comment by iVanlIsh** [comment]
@xhzdeng 
~~~
Solving...
F0516 16:19:09.485952 18831 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
experiments/scripts/train.sh: line 59: 18831 Aborted                 (core dumped) ./tools/train_net.py --gpu 0 --solver models/${NET}/solver.pt --weights ${WEIGHTS} --imdb ${TRAIN_IMDB} --iters ${ITERS} --cfg models/${NET}/config.yml ${EXTRA_ARGS}
~~~

**Comment by xhzdeng** [comment]
@iVanlIsh As you see, it is out of memory, you need 8GB GPU memory at least for training.

**Comment by iVanlIsh** [comment]
@xhzdeng But my GPU has 11177MiB.

**Comment by xhzdeng** [comment]
@iVanlIsh Is there some other programs occupied your GPU?

**Comment by iVanlIsh** [comment]
No. @xhzdeng

**Comment by xhzdeng** [comment]
maybe [this](https://blog.csdn.net/w5688414/article/details/79968100) will help you. ^_^
