### ISSUE TITLE
train.sh

### ISSUE THREAD

**Issue by zq130320339** [xhzdeng/crpn#9]
[723.29144  542.9097   723.29144  552.94037  723.29144  552.94037
  723.29144  542.9097  ]
 [270.              nan 723.29144  555.44806  270.              nan
  723.29144  557.9557  ]
 [723.29144  560.4634   723.29144  562.97107  723.29144  562.97107
  723.29144  560.4634  ]]
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/zq/crpn/tools/../lib/fast_rcnn/train.py", line 162, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/zq/crpn/tools/../lib/fast_rcnn/train.py", line 103, in train_model
    self.solver.step(1)
  File "/home/zq/crpn/tools/../lib/rpn/labelmap_layer.py", line 66, in forward
    x2 = int(round(bbox[2] * spatial_scale))
ValueError: cannot convert float NaN to integer

这样的错误是要删除对应的图片吗,还是修改sort_points中的代码?

**Comment by xhzdeng** [comment]
是需要删除包含nan的数据。你的数据好像有问题，x轴坐标都一样。
